# Numpy

0807

In [1]:
import numpy as np
import datetime

## 속도 비교

In [12]:
#list 작업 시간
li = range(1, 1000000)

#현재 시간
s = datetime.datetime.now()
print('시작시간:',s)

#모든 요소에 10을 곱해서 list 수정
for i in li:
    i = i*10
    
end = datetime.datetime.now()

print('종료 시간:',end)
print(end - s)

시작시간: 2023-08-07 15:27:33.244225
종료 시간: 2023-08-07 15:27:33.354231
0:00:00.110006


In [15]:
ar = np.arange(1, 1000000)
s = datetime.datetime.now()
print("시작시간:",s)
ar = ar * 10
end = datetime.datetime.now()
print('종료 시간:',end)
print(end - s)

시작시간: 2023-08-07 15:29:10.068767
종료 시간: 2023-08-07 15:29:10.071773
0:00:00.003006


## 배열의 정보 확인

In [19]:
ar = np.array([1,2,3])
 
print(type(ar)) #ar의 자료형
print(ar.dtype) #ar에 저장된 요소의 자료형
print(ar.ndim) #일차원 배열
print(ar.shape) #3개의 행으로 구성

<class 'numpy.ndarray'>
int32
1
(3,)


In [22]:
ar = np.array([[1,2,3],[4,5,6]])
print(ar.ndim) #2차원 배열
print(ar.shape) #2행 3열

2
(2, 3)


## 생성 함수

In [23]:
ar = np.arange(1, 100, 2)
print(ar)

ar = np.linspace(1, 100, num = 10)
print(ar)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## 특수 행렬

In [25]:
#eye - 대각 행렬
ar = np.eye(3) #3*3 행렬 생성, 대각선 방향으로 1을 채움
print(ar)
ar = np.eye(3, k= 1) #3*3 행렬 생성, 대각선 방향으로 1을 채우는데 기본에서 1위로
print(ar)
ar = np.eye(3, k= -1) #3*3 행렬 생성, 대각선 방향으로 1을 채우는데 기본에서 1아래로
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [28]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
 
br = np.diag(ar) #대각선 방향이므로 1,5,9
print(br)

cr = np.diag(ar, k = -1) #기본 대각선에서 하나 아래로 내려가므로 4, 8
print(cr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[4 8]


## dtype

In [29]:
ar = np.array(['1','2','3']) #문자열로 배열 생성
print(ar)
#자료형 변경
ar = np.array([1,2,'3'], dtype = np.int32) #정수로 배열이 생성 - 자료형 지정
print(ar)

ar = np.array([1,2,'3']) #문자열로 배열이 생성
print(ar)

br = ar.astype(np.int32) #기존 배열의 자료형을 변경해서 생성
print(br)

['1' '2' '3']
[1 2 3]
['1' '2' '3']
[1 2 3]


## 행렬의 차원 변환

In [32]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]]) #3*3행렬
print(matrix)

ar = matrix.reshape(-1) #1차원 변환 - 접근 방법을 변환한 것이라서 이전과 동일한 데이터
print(ar)
ar[0] = 101
ar, matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


(array([101,   2,   3,   4,   5,   6,   7,   8,   9]),
 array([[101,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]))

In [35]:
br = matrix.flatten() #복제 해서 1차원으로 변경 - 원본과 다른 데이터 생성
br[0] = 201
br, matrix

(array([201,   2,   3,   4,   5,   6,   7,   8,   9]),
 array([[101,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]))

## indexing

In [45]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix) #전체 출력 
print(matrix[0][1]) #0번째 열 1번째 행
print(matrix[0]) #0번째 행 전체 - 0번째 행을 선택할 때는 열 인덱스 제외
print(matrix[:,0]) #0번째 열 전체 - 열을 선택할 때는 전체라고 설정을 해야 함
#행렬 구조가 있을 때 행을 먼저 선택하고 열을 선택하기 때문에 행은 생략할 수 없음
print(matrix[0:2]) #0번째 행부터 2번째 행 앞까지

#일반 인덱싱은 참조를 복사 
x = matrix[0][0]
print(x)
print(matrix[0][0])
#현재는 둘 다 1

x = 1004
print(x)
print(matrix[0][0]) #[행 번호][열 번호] 로 접근 하는 것이 slicing, [행 번호, 열번호] 로 접근 하는 것 indexing
#slicing 은 복제함
#indexing은 참조를 복사합니다 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3]
[1 4 7]
[[1 2 3]
 [4 5 6]]
1
1
1004
1


## fancy indexing

In [47]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix) #전체 출력

#0번 행을 indexing - 참조를 복사
ar = matrix[0]
br = matrix[0,]
print(ar) #[1,2,3]
print(br)

#ar의 0번째 요소를 100으로 수정
ar[0] = 100
print(ar) #[100, 2, 3]
print(br) #[100, 2, 3]
print(matrix) #[100, 2, 3]

#list를 이용하는 인덱싱 = fancy indexing
cr = matrix[[0]]
#범위를 이용하는 형태 = slicing
dr = matrix[0][:]
#팬시 인덱싱과 슬라이싱은 복제를 함
#복제된 데이터를 수정해도 원본에 영향을 주지 X
print(cr)
print(dr)
cr[0,0] = 1004
print(cr) #[1004, 2, 3]
print(dr) #[100, 2, 3]
print(matrix) #[[100, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[[100   2   3]]
[100   2   3]
[[1004    2    3]]
[100   2   3]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


## boolean indexing

In [50]:
ar = np.array([10,2,30,5,22,37])
br = np.array([1,2,3,4,5,6])

print(br[ar >= 30])
print(br[(ar >= 30) | (ar <= 10)])

[3 6]
[1 2 3 4 6]


------

0808

## recap - indexing

In [3]:
#일차원 배열과 이차원 배열 생성
li = list(range(1,10))
print(li)

#list를 이용해서 ndarray 생ㅇ성
ar = np.array(li)
print(ar)

matrix = np.array(li).reshape((3,3)) #일차원 배열을 생성한 후 행과 열의 계수를 3*3으로 변경
print(matrix)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#인덱싱 - 데이터 가져오기
#scala data를 복사하는 경우는 원본의 값을 복사해서 대입하기 때문에 서로 간에 영향을 주지 X
data1 = ar[0]
data1 = 100
print(data1, ar)

#2차원 배열에서 데이터 1개 찾아오기
data2 = matrix[0,0]
data3 = matrix[0][0]
print(data2, data3)

#2차원 배열에서 행 1개 찾아오기
row = matrix[0] #matrix[0][:]
#2차원 배열에서 열 1개 찾아오기
column = matrix[:,1] #:은 전체를 의미함
print(row, column)

#row는 scala data(primitive type) X, vector data(non-primitive type) -> vector data를 다른 곳에 대입하면 참조가 복사됨
#따라서 복사본을 수정하면 원본도 영향을 받음
row[0] = 1004
print(row)
print(matrix)

100 [1 2 3 4 5 6 7 8 9]
1004 1004
[1004    2    3] [2 5 8]
[1004    2    3]
[[1004    2    3]
 [   4    5    6]
 [   7    8    9]]


In [14]:
#일반 인덱싱한 데이터는 파이썬의 기본 데이터와 동일하게 동작함
#python의 scala data -> immutable = 변경 불가
#scala 데이터는 다른 변수에 대입할 때 값을 복사해서 대입함
a = 10
b = a
b = 20
print(a)

#python의 vector data는 다른 변수에 대입할 때 참조를 복사해서 대입함
ax =  [1,2,3]
bx = ax
bx[0] = 100
ax

[100, 2, 3]

## data copy - copy method

In [23]:
#python에서의 data 복제
#copy 모듈 의 copy(얕은 복사)와 deepcopy(깊은 복사) 함수 이용
#얕은 복사는 한 번은 복제를 하지만 재귀적으로 수행X
#깊은 복사는 재귀적으로 복제 수행
from copy import copy, deepcopy

li = [1,2,3]
c = li.copy() #얕은 복사
c[0] = 100 #일차원 list의 경우는 원본에 영향을 주지 않음
print(c, li)

m = [[1,2,3],[4,5,6]]
c = m.copy()
c[0][0] = 100 #얕은 복사는 2차원 배열의 경우는 원본에 영향을 줌
print(c, m)

d = deepcopy(m)
d[0][0] = 1004 #깊은 복사는 재귀적으로 복제를 수행하기 때문에 복사본에서 데이터를 수정해도 원본에 영향 X
print(d, m)

#데이터 복제는 copy method 사용
clone = matrix.copy() #복사본
clone[0][0] = 1 #복사본의 데이터를 수정해도 원본에서는 그대로 1004
print(clone)
print(matrix)

#matrix는 np array, m은 list array

[100, 2, 3] [1, 2, 3]
[[100, 2, 3], [4, 5, 6]] [[100, 2, 3], [4, 5, 6]]
[[1004, 2, 3], [4, 5, 6]] [[100, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1004    2    3]
 [   4    5    6]
 [   7    8    9]]


## slicing - list vs np array

In [37]:
li = [1,2,3]
c = li[0:3] #list의 slicing
#c 와 li는 앞 3개의 데이터가 동일하지만 다른 공간의 데이터
print(c)
c[0] = 100 #c의 값을 변경해도 li에는 영향이 없음
print(c, li)

ar = np.array(li)
d = ar[0:3] #배열에서 0-2까지 데이터 복사 -> 데티어 개수 3개 = vector data = 참조 복사
print(d)
d[0] = 100 #참조를 복사했기 때문에 값을 수정하면 영향을 주게 됨
print(d, ar)

c is li #가리키는 데이터가 같은지 다른지 비교

[1, 2, 3]
[100, 2, 3] [1, 2, 3]
[1 2 3]
[100   2   3] [100   2   3]
[100, 2, 3] [1, 2, 3]


False

## fancy indexing

In [39]:
#indexing을 할 때 list를 이용하는 것
ar = np.array([100,200,300,400,500])
f = ar[[0,2]]
print(f)
f[0] = 1004 #영향 X
print(ar)

[100 300]
[100 200 300 400 500]


## bool indexing

In [49]:
print(bool(1))
print(bool([1,2,3]))
#print(bool([1,2,3] > 2)) #비교하기 위해서는 데이터의 크기 / 타입이 같아야함
#python은 비교를 위해 비교하고자 하는 데이터가 참조인지 값인지 먼저 파악 = 비교 대상 파악 먼저

#boolean index: array의 인덱스에 bool 배열을 대입해서 True인 데이터만 골라내기
ar = np.array([1,2,3,4,5,6,7])
result = ar[[True, True, False, False, True, False, True]]
print(result)

br = np.array([10,20,30,40,50,80,90])
result = ar[(br >= 70) &(br <= 90)]
print(result)

True
True
[1 2 5 7]
[6 7]


# ndarry의 연산

## 산술 연산

In [62]:
ar = np.array([1,2,3,4,5])
br = np.array([10,20,30,40,50])

result = ar + br
result

result = ar+4 #2개의 차원이 다른 경우로 이 경우는 적인 차원의 데이터를 큰 차원의 데이터로 수정
result

k = range(1,11)
#일차원 배열을 2행 5열로 수정해서 연산 수행
cr = np.array(k).reshape((2,5))
#cr + ar #data의 개수가 맞지 않아 error
cr + ar

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

## 논리 연산

In [64]:
ar = np.array([1,2,3,4,5])
br = np.array([10,20,False, 40, 0])

print(ar > br)
print(np.not_equal(ar, br))
#and, or, xor는 bool(True, False)로 변경해서 판정
print(np.logical_xor(ar, br)) #xor는 같으면 False, 다르면 True -> 데이터의 값이 아닌 bool 값으로 연산 수행

[False False  True False  True]
[ True  True  True  True  True]
[False False  True False  True]


## 연산 후 할당 가능

In [65]:
ar += br # ar = ar + br
ar

array([11, 22,  3, 44,  5])

## in / not in

In [67]:
print(1 in ar)
print([1,2] in ar)
print([1,100] in ar)

False
False
False


C:\Users\USER\AppData\Local\Temp\ipykernel_17168\330414030.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([1,2] in ar)
C:\Users\USER\AppData\Local\Temp\ipykernel_17168\330414030.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([1,100] in ar)


# vectorization

In [69]:
#vector화 된 함수 적용
#매개 변수에 100을 더해서 리턴하는 함수

def f(i):
    return i + 100

#백터화 된 함수로 수정
vector_f = np.vectorize(f)
#배열에 벡터화 된 함수 적용
print(vector_f(ar))

#람다 함수(python의 한 줄 짜리 이름 없는 함수)를 이용해서 동일한 작업 수행
print(np.vectorize(lambda i: i+100)(ar))

[111 122 103 144 105]
[111 122 103 144 105]


## 전치

In [73]:
matrix = np.array(range(1, 11)).reshape((5,2))
print(matrix)
print(matrix.reshape((2,5))) #행과 열의 수를 변경
print(matrix.T) #행과 열을 변경
print(np.transpose(matrix)) #행과 열을 변경

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


# numpy 함수

## random

In [78]:
np.random.seed(seed = 42) #seed 고정
cards = np.array(range(1, 49)) #1~48까지 일차원 배열
print(cards)
#배열을 섞어서 return
result = np.random.permutation(cards)
result

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


array([28, 41, 27, 44, 25, 38, 13, 20,  5, 26,  9,  4,  7, 40, 34, 14, 18,
       46, 16, 10, 17, 30, 33, 47,  1, 32, 31,  6, 12, 35,  2, 45, 22,  3,
       37, 36, 24, 42, 11, 23, 19, 48, 21,  8, 43, 15, 29, 39])

## 기본 통계 함수

In [89]:
matrix = np.array([[10,20],[30,40],[50,60]])
#matrix = np.random.randn(20).reshape((4,5))
print(matrix)

print(matrix.sum())
print(matrix.std()) #표준 편차
print(matrix.std(ddof = 1)) #표준 편차 - 자유도 1 적용
print(np.percentile(matrix, 75))

#행 단위, 열 단위
print(matrix.sum(axis = 0)) # 열 단위 계산
print(matrix.sum(axis = 1)) # 행 단위 계산
print(matrix.sum(axis = 1, keepdims = True)) #행 단위 - matrix와 동일한 차원으로 return

print(matrix.argmax(axis = 0)) #index를 return
print(matrix.cumprod()) #누적 곱

[[10 20]
 [30 40]
 [50 60]]
210
17.07825127659933
18.708286933869708
47.5
[ 90 120]
[ 30  70 110]
[[ 30]
 [ 70]
 [110]]
[2 2]
[       10       200      6000    240000  12000000 720000000]


## data 정렬

In [92]:
#일차원 배열 정렬
ar = np.array([20,30,20,25,27])
result = np.sort(ar) #데이터를 정렬
print(result)
print(ar)

#2차원 배열의 행에서의 정렬 -> 2차원 배열은 열 또는 행을 기준으로 정렬 
br = np.array([[10,60,80],[20,50,30],[15,32,29]])
result = np.sort(br, axis = 1) 
print(result)

[20 20 25 27 30]
[20 30 20 25 27]
[[10 60 80]
 [20 30 50]
 [15 29 32]]


# 분할 과 병합

## split

In [111]:
x = range(1, 51)
#위의 데이터를 가지고 10행 5열 2차원 데이터 생성
matrix = np.array(x).reshape((10,5))

#행과 열의 개수 알아오기
print(matrix.shape)
print(type(matrix.shape))

#data를 7:3 분할
cnt = matrix.shape[0]
print(cnt)

#여기에 permutation을 적용하면 sampling 해주는 함수가 됨
np.split(matrix, [int(cnt * 0.7)])
#result
#help(np.split)

(10, 5)
<class 'tuple'>
10
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]]),
 array([[36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]])]